name: Cache Practice

on: workflow_dispatch   # запускаємо вручну кнопкою, щоб контролювати кожен запуск

jobs:
  test-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Cache node_modules
        id: cache-npm
        uses: actions/cache@v5
        with:
          path: actions_cache/node_modules
          key: npm-${{ hashFiles('actions_cache/package-lock.json') }}

      - name: Show cache status
        run: echo "Cache hit? -> ${{ steps.cache-npm.outputs.cache-hit }}"

      - name: Install dependencies (timed)
        working-directory: actions_cache
        run: |
          echo "Start: $(date +%s)"
          npm install
          echo "End: $(date +%s)"
